---
dependencies:
  cupertino_icons: ^1.0.4
  dropdown_button2: ^1.4.0
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^3.0.1
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  get: ^4.6.1
  google_maps_flutter: ^2.1.3
  import_sorter: ^4.6.0
  introduction_screen: ^3.0.2
  logger: ^1.1.0
  marquee: ^2.2.1
  ndialog: ^4.1.1
  simple_animations: ^4.0.1
  text_scroll: ^0.0.4
description: A new Flutter project.
dev_dependencies:
  build_runner: null
  flutter_gen_runner: null
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
environment:
  sdk: ">=2.16.2 <3.0.0"
flutter:
  assets:
    - assets/images/
    - assets/images/login_screen/
    - assets/images/onboard_1st/
    - assets/images/onboard_2nd/
    - assets/images/sign_up/
    - assets/images/svgs/
  uses-material-design: true
flutter_gen:
  integrations:
    flare_flutter: false
    flutter_svg: true
    rive: false
  line_length: 80
  output: lib/gen/
name: kuseng
publish_to: none
version: 1.0.0+1
